config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "home#index"
  namespace :admin do
    get "/", to: "home#index"
    resources :users
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :articles
    resources :categories, except: [:show]
    resources :article_files
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end
  resources :articles, only: :index
  namespace :ranking do
    get "pv", to: "articles#index"
    get "pv/:category_name", to: "articles#index"
    get "comment", to: "articles#index"
    get "comment/:category_name", to: "articles#index"
    get "user/pv", to: "users#index"
    get "user/pv/:category_name", to: "users#index"
    get "user/comment", to: "users#index"
    get "user/comment/:category_name", to: "users#index"
  end
  resources :comments, only: [:create]
  get "pages/:slug", to: "articles#show", as: :article
  get "pages/:category_name/:slug", to: "articles#show", as: :category_article
  mount Sidekiq::Web, at: "/sidekiq"
  namespace :admin do
    get "*path", controller: "base", action: "render_404"
  end
  get "*path", controller: "application", action: "render_404"
end

app/models/article.rb
class Article < ApplicationRecord
  extend Enumerize
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true
  validates :slug, presence: true, uniqueness: true
  has_many :article_histories
  has_many :comments, dependent: :destroy
  has_many :daily_article_summaries, dependent: :destroy
  has_many :weekly_article_summaries, dependent: :destroy
  has_many :monthly_article_summaries, dependent: :destroy
  belongs_to :category, optional: true
  belongs_to :user
  paginates_per 10
  acts_as_paranoid
  enumerize :status, in: { draft: 0, release: 1 }, default: :draft, predicates: true, scope: true

  scope :order_created_at_desc, -> { order(created_at: :desc) }
  scope :released_articles, -> { with_status(:release).where("released_at <= ?", Time.zone.now) }

  def update_with_history!
    ActiveRecord::Base.transaction do
      save!
      ArticleHistory.create_article_history!(self)
    end
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::BaseController
    def index
      @form = Admin::Articles::SearchForm.new(search_params)
      @articles = @form.search(params[:page])
    end

    def show
      @article = Article.find(params[:id])
    end

    def new
      @article = Article.new
    end

    def create
      @article = current_user.articles.build(article_params)
      if @article.save
        redirect_to admin_articles_path, notice: "記事を作成しました"
      else
        render :new
      end
    end

    def edit
      @article = current_user.articles.find(params[:id])
    end

    def update
      @article = current_user.articles.find(params[:id])
      @article.attributes = article_params
      if @article.update_with_history!
        redirect_to admin_articles_path, notice: "記事を更新しました"
      else
        render :edit
      end
    end

    def destroy
      @article = Article.find(params[:id])
      raise ActiveRecord::RecordNotFound  unless @article.user_id == current_user.id
      if @article.destroy
        redirect_to admin_articles_path, notice: "記事を削除しました"
      else
        flash.now[:danger] = "記事の削除に失敗しました"
        render :edit
      end
    end

    private

      def article_params
        params.require(:article).permit(:title, :content, :slug, :image_url, :category_id, :status, :released_at)
      end

      def search_params
        params.fetch(:admin_articles_search_form, {}).permit(:status, :title, :category_id, :max_released_at, :min_released_at)
      end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @form = Articles::SearchForm.new(search_params)
    @articles = @form.search(params[:page])
  end

  def show
    @article = Article.find(params[:article_id])
    @article.increment!(:pv_count)
    @comments = @article.comments
    @comment = @article.comments.build
  end

  private

  def search_params
    params.fetch(:articles_search_form, {}).permit(:title, :category_id)
  end
end

app/controllers/ranking/articles_controller.rb
module Ranking
  class ArticlesController < ApplicationController
    def index
      @form = Ranking::Articles::SearchForm.new(search_params)
      @articles = @form.search
      @categories = Category.all
    end

    private

    def search_params
      params[:path] = request.path
      params.permit(:term, :category_name, :path)
    end
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.slim
.col-md-7.mx-auto
  h1 記事一覧
.col-md-7.mx-auto.mb-5
  .card
    = form_with model: @form, url: articles_path, method: :get, local: true do |f|
      .search_box
        .card-body
          h3 検索フォーム
          .form-group
            = f.label :title, "記事のタイトル"
            = f.text_field :title, class: "form-control"
          .form-group
            = f.label :category_id, "カテゴリ"
            = f.collection_select :category_id, Category.all, :id, :name, { include_blank: "選択してください" }, class: "form-control"
        .card-footer.bg-white
          = f.submit "検索", class: "btn btn-primary"

.news-container.col-md-7.mx-auto.pb-5
  .row.row-cols-1.row-cols-md-2
    - @articles.each do |article|
      .col.mb-3
        .card.h-100
          - if article.category.nil?
            = link_to article_path(article.slug, article_id: article.id), class: "news-link" do
              .news-image = image_tag(article.image_url.to_s)
              .card-body
                h4.card-title.font-weight-bold.text-body = article.title
                p.text-secondary 公開日：#{ l article.released_at, format: :date }
          - else
            = link_to category_article_path(slug: article.slug, category_name: article.category.name, article_id: article.id), class: "news-link" do
              .news-image = image_tag(article.image_url.to_s)
              .card-body
                h4.card-title.font-weight-bold.text-body = article.title
                p.text-secondary 公開日：#{ l article.released_at, format: :date }
  br
  = paginate @articles

app/views/articles/show.html.slim
.contents-container.col-md-6.mx-auto
  h3 記事本文

  .contents-area.mx-auto.px-3
    .news
      .news-title
        h4.font-weight-bold
          = @article.title
        .font-italic
          p 公開日：#{ l @article.released_at, format: :date }
      .news-content = simple_format(@article.content)

  br
  = form_with model: @comment, url: comments_path, local: true do |f|
    = hidden_field_tag :article_id, @article.id
    .form-group
      = f.label :comment, "コメント"
      = f.text_area :comment, class: "form-control", placeholder: "コメントを書く"
    = f.submit "投稿する", class: "btn btn-primary"
  br
  .comment-area
    h3 コメントエリア
    - @comments.each do |comment|
      .comment-wrapper.border-bottom
        .comment.col-md-10.mx-auto
          = simple_format(comment.comment)