config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "home#index"
  namespace :admin do
    get "/", to: "home#index"
    resources :users
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :articles
    resources :categories, except: [:show]
    resources :article_files
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end
  resources :articles, only: :index
  namespace :ranking do
    get "pv", to: "articles#index"
    get "pv/:category_name", to: "articles#index"
    get "comment", to: "articles#index"
    get "comment/:category_name", to: "articles#index"
    get "user/pv", to: "users#index"
    get "user/pv/:category_name", to: "users#index"
    get "user/comment", to: "users#index"
    get "user/comment/:category_name", to: "users#index"
  end
  resources :comments, only: [:create]
  get "pages/:slug", to: "articles#show", as: :article
  get "pages/:category_name/:slug", to: "articles#show", as: :category_article
  mount Sidekiq::Web, at: "/sidekiq"
  namespace :admin do
    get "*path", controller: "base", action: "render_404"
  end
  get "*path", controller: "application", action: "render_404"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :nullify
  validates :name, uniqueness: true, presence: true, length: { maximum: 191 }
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::BaseController
    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path, notice: "カテゴリーを作成しました"
      else
        render :new
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        redirect_to admin_categories_path, notice: "カテゴリーを編集しました"
      else
        render :edit
      end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy!
      redirect_to admin_categories_path, notice: "カテゴリー「#{@category.name}」を削除しました"
    end

    private

      def category_params
        params.require(:category).permit(:name)
      end
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.slim
- if category.errors.any?
  ul#error_explanation
    - category.errors.full_messages.each do |message|
      li = message

= form_with model: category, url: url, local: true do |f|
  .card-body
    .form-group
      = f.label :name, "カテゴリー名"
      = f.text_field :name, class: "form-control"
  .card-footer
    = f.submit "作成", class: "btn btn-primary"

app/views/admin/categories/edit.html.slim
.col-md-4
  .card
    .card-header
      h1 カテゴリー編集

    = render "form", category: @category, url: admin_category_path(@category)

app/views/admin/categories/index.html.slim
.col-md-7.mb-5
  .card
    .card-header
      h1.d-inline.mr-3 カテゴリー一覧
      button.btn.btn-secondary.align-text-bottom
        = link_to "新規作成", new_admin_category_path, class: "file-link font-weight-bold"

    .card-body.table-responsive
      table.table-bordered.table
        thead
          tr
            th カテゴリー名
            th アクション
        tbody
          - @categories.each do |category|
            tr
              td = category.name
              td
                = link_to "編集", edit_admin_category_path(category), class: 'btn btn-primary mr-3'
                = link_to "削除", admin_category_path(category), method: :delete, data: { confirm: "カテゴリー#{category.name}を削除します。よろしいですか？" }, class: "btn btn-danger"

app/views/admin/categories/new.html.slim
.col-md-4
  .card
    .card-header
      h1 カテゴリー作成

    = render "form", category: @category, url: admin_categories_path