config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "home#index"
  namespace :admin do
    get "/", to: "home#index"
    resources :users
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :articles
    resources :categories, except: [:show]
    resources :article_files
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end
  resources :articles, only: :index
  namespace :ranking do
    get "pv", to: "articles#index"
    get "pv/:category_name", to: "articles#index"
    get "comment", to: "articles#index"
    get "comment/:category_name", to: "articles#index"
    get "user/pv", to: "users#index"
    get "user/pv/:category_name", to: "users#index"
    get "user/comment", to: "users#index"
    get "user/comment/:category_name", to: "users#index"
  end
  resources :comments, only: [:create]
  get "pages/:slug", to: "articles#show", as: :article
  get "pages/:category_name/:slug", to: "articles#show", as: :category_article
  mount Sidekiq::Web, at: "/sidekiq"
  namespace :admin do
    get "*path", controller: "base", action: "render_404"
  end
  get "*path", controller: "application", action: "render_404"
end

app/models/article.rb
class Article < ApplicationRecord
  extend Enumerize
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true
  validates :slug, presence: true, uniqueness: true
  has_many :article_histories
  has_many :comments, dependent: :destroy
  has_many :daily_article_summaries, dependent: :destroy
  has_many :weekly_article_summaries, dependent: :destroy
  has_many :monthly_article_summaries, dependent: :destroy
  belongs_to :category, optional: true
  belongs_to :user
  paginates_per 10
  acts_as_paranoid
  enumerize :status, in: { draft: 0, release: 1 }, default: :draft, predicates: true, scope: true

  scope :order_created_at_desc, -> { order(created_at: :desc) }
  scope :released_articles, -> { with_status(:release).where("released_at <= ?", Time.zone.now) }

  def update_with_history!
    ActiveRecord::Base.transaction do
      save!
      ArticleHistory.create_article_history!(self)
    end
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::BaseController
    def index
      @form = Admin::Articles::SearchForm.new(search_params)
      @articles = @form.search(params[:page])
    end

    def show
      @article = Article.find(params[:id])
    end

    def new
      @article = Article.new
    end

    def create
      @article = current_user.articles.build(article_params)
      if @article.save
        redirect_to admin_articles_path, notice: "記事を作成しました"
      else
        render :new
      end
    end

    def edit
      @article = current_user.articles.find(params[:id])
    end

    def update
      @article = current_user.articles.find(params[:id])
      @article.attributes = article_params
      if @article.update_with_history!
        redirect_to admin_articles_path, notice: "記事を更新しました"
      else
        render :edit
      end
    end

    def destroy
      @article = Article.find(params[:id])
      raise ActiveRecord::RecordNotFound  unless @article.user_id == current_user.id
      if @article.destroy
        redirect_to admin_articles_path, notice: "記事を削除しました"
      else
        flash.now[:danger] = "記事の削除に失敗しました"
        render :edit
      end
    end

    private

      def article_params
        params.require(:article).permit(:title, :content, :slug, :image_url, :category_id, :status, :released_at)
      end

      def search_params
        params.fetch(:admin_articles_search_form, {}).permit(:status, :title, :category_id, :max_released_at, :min_released_at)
      end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @form = Articles::SearchForm.new(search_params)
    @articles = @form.search(params[:page])
  end

  def show
    @article = Article.find(params[:article_id])
    @article.increment!(:pv_count)
    @comments = @article.comments
    @comment = @article.comments.build
  end

  private

  def search_params
    params.fetch(:articles_search_form, {}).permit(:title, :category_id)
  end
end

app/controllers/ranking/articles_controller.rb
module Ranking
  class ArticlesController < ApplicationController
    def index
      @form = Ranking::Articles::SearchForm.new(search_params)
      @articles = @form.search
      @categories = Category.all
    end

    private

    def search_params
      params[:path] = request.path
      params.permit(:term, :category_name, :path)
    end
  end
end

app/controllers/ranking/users_controller.rb
module Ranking
  class UsersController < ApplicationController
    def index
      @form = Ranking::Users::SearchForm.new(search_params)
      @users = @form.search
    end

    private

    def search_params
      params[:path] = request.path
      params.permit(:term, :path)
    end
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/ranking/articles/index.html.slim
.col-md-5.mx-auto
  - if params[:path].include?("/comment")
    h1 コメントランキング
  - elsif params[:path].include?("/pv")
    h1 PVランキング
  = link_to "pvランキング", ranking_pv_path
  = link_to "コメントランキング", ranking_comment_path
  = link_to "ユーザPVランキング", ranking_user_pv_path
  = link_to "ユーザコメントランキング", ranking_user_comment_path
.col-md-5.mx-auto.mb-5
  p 集計時間
  .dropdown
    button#dropdownMenuButton.btn.btn-secondary.dropdown-toggle[type="button" data-toggle="dropdown" aria-expanded="false"]
      - if params[:term]
        = "#{{ "daily": "24時間", "weekly": "週間", "monthly": "月間" }[params[:term].to_sym]}"
      - else
        | 24時間
    .dropdown-menu[aria-labelledby="dropdownMenuButton"]
      - if params[:category_name].present? && params[:path].include?("/pv")
        = link_to "24時間", ranking_path(category_name: params[:category_name], term: "daily"), class: "dropdown-item"
        = link_to "週間", ranking_path(category_name: params[:category_name], term: "weekly"), class: "dropdown-item"
        = link_to "月間", ranking_path(category_name: params[:category_name], term: "monthly"), class: "dropdown-item"
      - elsif params[:path].include?("/pv")
        = link_to "24時間", ranking_pv_path(term: "daily"), class: "dropdown-item"
        = link_to "週間", ranking_pv_path(term: "weekly"), class: "dropdown-item"
        = link_to "月間", ranking_pv_path(term: "monthly"), class: "dropdown-item"
      - elsif params[:path].include?("/comment")
        = link_to "24時間", ranking_comment_path(category_name: params[:category_name], term: "daily"), class: "dropdown-item"
        = link_to "週間", ranking_comment_path(category_name: params[:category_name], term: "weekly"), class: "dropdown-item"
        = link_to "月間", ranking_comment_path(category_name: params[:category_name], term: "monthly"), class: "dropdown-item"
.news-container.col-md-5.mx-auto.pb-5
  - @categories.each do |category|
    = link_to category.name, ranking_comment_path(category_name: category.name, term: params[:term])
  .row.row-cols-1
    - @articles.each do |article|
      .col.mb-3
        .card.h-100
          - if article.category.nil?
            = link_to article_path(article.slug, article_id: article.id), class: "news-link" do
              .news-image = image_tag(article.image_url.to_s)
              .card-body
                h4.card-title.font-weight-bold.text-body = article.title
                p.text-secondary 公開日：#{ l article.released_at, format: :date }
          - else
            = link_to category_article_path(slug: article.slug, category_name: article.category.name, article_id: article.id), class: "news-link" do
              .news-image = image_tag(article.image_url.to_s)
              .card-body
                h4.card-title.font-weight-bold.text-body = article.title
                p.text-secondary 公開日：#{ l article.released_at, format: :date }

app/views/ranking/articles/pv.html.slim
.col-md-5.mx-auto
  h1 pvランキング
  = render "ranking/header"
.col-md-5.mx-auto.mb-5
  p 集計時間
  .dropdown
    button#dropdownMenuButton.btn.btn-secondary.dropdown-toggle[type="button" data-toggle="dropdown" aria-expanded="false"]
      - if params[:term]
        = "#{{ "daily": "24時間", "weekly": "週間", "monthly": "月間" }[params[:term].to_sym]}"
      - else
        | 24時間
    .dropdown-menu[aria-labelledby="dropdownMenuButton"]
      - if params[:category_name]
        = link_to "24時間", ranking_path(category_name: params[:category_name], term: "daily"), class: "dropdown-item"
        = link_to "週間", ranking_path(category_name: params[:category_name], term: "weekly"), class: "dropdown-item"
        = link_to "月間", ranking_path(category_name: params[:category_name], term: "monthly"), class: "dropdown-item"
      - else
        = link_to "24時間", ranking_pv_path(term: "daily"), class: "dropdown-item"
        = link_to "週間", ranking_pv_path(term: "weekly"), class: "dropdown-item"
        = link_to "月間", ranking_pv_path(term: "monthly"), class: "dropdown-item"
.news-container.col-md-5.mx-auto.pb-5
  - @categories.each do |category|
    = link_to category.name, ranking_path(category_name: category.name, term: params[:term])
  .row.row-cols-1
    - @articles.each do |article|
      .col.mb-3
        .card.h-100
          - if article.category.nil?
            = link_to article_path(article.slug, article_id: article.id), class: "news-link" do
              .news-image = image_tag(article.image_url.to_s)
              .card-body
                h4.card-title.font-weight-bold.text-body = article.title
                p.text-secondary 公開日：#{ l article.released_at, format: :date }
          - else
            = link_to category_article_path(slug: article.slug, category_name: article.category.name, article_id: article.id), class: "news-link" do
              .news-image = image_tag(article.image_url.to_s)
              .card-body
                h4.card-title.font-weight-bold.text-body = article.title
                p.text-secondary 公開日：#{ l article.released_at, format: :date }