config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "home#index"
  namespace :admin do
    get "/", to: "home#index"
    resources :users
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :articles
    resources :categories, except: [:show]
    resources :article_files
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end
  resources :articles, only: :index
  namespace :ranking do
    get "pv", to: "articles#index"
    get "pv/:category_name", to: "articles#index"
    get "comment", to: "articles#index"
    get "comment/:category_name", to: "articles#index"
    get "user/pv", to: "users#index"
    get "user/pv/:category_name", to: "users#index"
    get "user/comment", to: "users#index"
    get "user/comment/:category_name", to: "users#index"
  end
  resources :comments, only: [:create]
  get "pages/:slug", to: "articles#show", as: :article
  get "pages/:category_name/:slug", to: "articles#show", as: :category_article
  mount Sidekiq::Web, at: "/sidekiq"
  namespace :admin do
    get "*path", controller: "base", action: "render_404"
  end
  get "*path", controller: "application", action: "render_404"
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  extend Enumerize
  enumerize :role, in: { general: 0, admin: 1 }, default: :general, predicates: true, scope: true
  attr_accessor :remember_token, :reset_password_token
  has_secure_password
  validates :email, presence: true, length: { maximum: 191 }, uniqueness: true
  has_many :articles
  has_many :daily_user_summaries, dependent: :destroy
  has_many :weekly_user_summaries, dependent: :destroy
  has_many :monthly_user_summaries, dependent: :destroy

  # 渡された文字列をハッシュ化して返す
  # min_cost == trueになるのはテスト時
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにトークンをDBに保存する
  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token), remember_created_at: Time.zone.now)
  end

  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update(remember_digest: nil, remember_created_at: nil)
  end

  def create_reset_password_token
    self.reset_password_token = User.new_token
    update_attributes!(reset_password_token_digest: User.digest(reset_password_token), reset_password_sent_at: Time.zone.now)
  end

  def password_reset_expired?
    reset_password_sent_at < 1.hours.ago
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :authorize_admin_user

  def index
    @admin_users = User.with_role(:admin)
  end

  def show
    @admin_user = User.with_role(:admin).find(params[:id])
  end

  def new
    @admin_user = User.new
  end

  def create
    @admin_user = User.new(admin_params)
    if @admin_user.save
      redirect_to admin_users_path, notice: "ユーザを登録しました"
    else
      render :new
    end
  end

  def edit
    @admin_user = User.with_role(:admin).find(params[:id])
  end

  def update
    @admin_user = User.with_role(:admin).find(params[:id])
    if @admin_user.update(admin_params)
      redirect_to admin_path(@admin_user), notice: "ユーザの情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @admin_user = User.with_role(:admin).find(params[:id])
    @admin_user.destroy!
    redirect_to admin_users_path, notice: "ユーザの情報を削除しました"
  end

  private

    def admin_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role)
    end
end

app/controllers/ranking/users_controller.rb
module Ranking
  class UsersController < ApplicationController
    def index
      @form = Ranking::Users::SearchForm.new(search_params)
      @users = @form.search
    end

    private

    def search_params
      params[:path] = request.path
      params.permit(:term, :path)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.slim
- if admin_user.errors.any?
  ul#error_explanation
    - admin_user.errors.full_messages.each do |message|
      li = message

= form_with model: admin_user, url: url, local: true do |f|
  .card-body
    .form-group
      = f.label :email, User.human_attribute_name(:email)
      .input-group.md-3
        .input-group-prepend
          span.input-group-text
            i.cil-user.c-icon
        = f.text_field :email, class: "form-control"
    .form-group
      = f.label :password, User.human_attribute_name(:password)
      .input-group.md-3
        .input-group-prepend
          span.input-group-text
            i.cil-lock-locked.c-icon
        = f.password_field :password, class: "form-control"
    .form-group
      = f.label :password_confirmation, User.human_attribute_name(:password_confirmation)
      .input-group.md-3
        .input-group-prepend
          span.input-group-text
            i.cil-lock-locked.c-icon
        = f.password_field :password_confirmation, class: "form-control"
    .form-check
      = f.label :role, class: "form-check-label" do
        = f.check_box :role, class: "form-check-input"
        | 管理者権限
  .card-footer
    = f.submit "登録する", class: "btn btn-primary"

app/views/admin/users/edit.html.slim
.col-md-5
  .card
    .card-header
      h1 ユーザ編集

    = render "form", admin_user: @admin_user, url: admin_user_path(@admin_user)

app/views/admin/users/index.html.slim
.col-md-8.mb-5
  .card
    .card-header
      h1.d-inline.mr-3 管理者一覧
      button.btn.btn-secondary.align-text-bottom
        = link_to "管理者登録", new_admin_user_path, class: "file-link font-weight-bold"

    .card-body.table-responsive
      table.table-bordered.table
        thead
          tr
            th = User.human_attribute_name(:email)
            th = User.human_attribute_name(:role)
            th アクション
        tbody
          - @admin_users.each do |admin_user|
            tr
              td = link_to admin_user.email, admin_user_path(admin_user)
              td = admin_user.role_text
              td
                = link_to "編集", edit_admin_user_path(admin_user), class: 'btn btn-primary mr-3'
                = link_to "削除", admin_user_path(admin_user), method: :delete, data: { confirm: "ユーザ#{admin_user.email}を削除します。よろしいですか？" }, class: "btn btn-danger"

app/views/admin/users/new.html.slim
.col-md-5
  .card
    .card-header
      h1 管理者ユーザ登録

    = render "form", admin_user: @admin_user, url: admin_users_path

app/views/admin/users/show.html.slim
.col-md-7.mb-5
  .card
    .card-header
      h3 ユーザ詳細
    .card-body.table-responsive
      table.table-bordered.table
        thead
          tr
            th = User.human_attribute_name(:email)
            th = User.human_attribute_name(:role)
            th アクション
        tbody
          tr
            td = @admin_user.email
            td = @admin_user.role_text
            td
              = link_to "編集", edit_admin_user_path(@admin_user), class: "btn btn-primary mr-3"
              = link_to "削除", admin_user_path(@admin_user), method: :delete, data: { confirm: "ユーザ#{@admin_user.email}を削除します。よろしいですか？" }, class: "btn btn-danger"